### PR TITLE
fix(opening apps): Use spawn/exec for opening of apps on all platforms.

### LINKED ISSUE #145: Opening application results in broken app instance
EG: after install, triggering opening of browser will open a browser window, but it will remain white.

Possibly related to the current working directory of the process being used...

### PR DESCRIPTION
**Pull request by joshuef**
Fixes #145 via spawn/exec depending on platform.
Removes HOT and dev env vars to enable page loads in app.

### CODE REVIEW

File: app/manageInstallations/helpers.ts [hunk 1]
```diff
@@ -59,6 +59,7 @@ export const getInstalledLocation = ( application: App ): string => {
     const applicationExecutable = getApplicationExecutable( application );
 
     const installedPath = path.join( INSTALL_TARGET_DIR, applicationExecutable );
+    console.log( 'merging ---->>>', installedPath );
```
Comment (shankar2105) [inline app/manageInstallations/helpers.ts]: Can we use the logger instead?

Comment (joshuef) [reply app/manageInstallations/helpers.ts]: actually this should just not be there! will remove and rebase now
